# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('follower', 'followed')]),
        ),
    ]
