# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170714_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
