# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170801_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
