# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170803_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
    ]
